### ISSUE TITLE
Why loop about event need twice

### ISSUE THREAD

**Issue by kissdata** [veandco/go-sdl2-examples#13]
When it comes to **Event**, most of code in examples look like this: 
```go
for event := sdl.PollEvent(); event != nil; event = sdl.PollEvent() {
    switch t := event.(type) {
    ...
    } 
}
```
Why the event (a interface) should be written `= sdl.PollEvent()` twice?

**Comment by veeableful** [comment]
Hi @kissdata, it is a standard for-loop in Go. You can see an explanation of it [here](https://go.dev/tour/flowcontrol/1).

We use it in the examples to extract all the Events in current frame until there's no more.

**Comment by kissdata** [comment]
I known it, for-loop with 3 expressions, so does in c/cpp.
I now reading the [article](https://www.willusher.io/sdl2%20tutorials/2013/08/20/lesson-4-handling-events) recommended by [wiki.libsdl.org](https://wiki.libsdl.org/SDL2/Tutorials) (ranked 6th) , he used a while-loop to process event:
```cpp
while (SDL_PollEvent(&e)) {
    if (e.type == SDL_QUIT) {
        // ...
    }
    if (e.type == SDL_KEYDOWN) {
        // ...
    }
}
```
oh 👀 so short, if I use `go` recode it, this for-loop looks longer than original statement. I want see if exists a better way to implement it.
