### ISSUE TITLE
Cursor unresponding

### ISSUE THREAD

**Issue by pouryatorabi** [veandco/go-sdl2-examples#3]
I have a problem with the cursor, it also occurs in the render example provided. The problem is if I move my mouse to the created window, it becomes unresponding.

**Comment by veeableful** [comment]
Hi @pouryatorabi, could you elaborate on what you mean by unresponding? What is your OS?

**Comment by pouryatorabi** [comment]
Hi, Actually I have tried both on Win and Linux, I just tried to hide my mouse cursor, but the cursor would show a busy indicator when I move it from outside the window to inside it. I hope you understand it, it is hard to explain :)))

**Comment by veeableful** [comment]
Hi @pouryatorabi, there is a 2-second sleep / freeze in the program after it finishes drawing which I guess causes the cursor to be busy. Does that match what you experienced? It is an intended outcome as of now.

**Comment by pouryatorabi** [comment]
> Hi @pouryatorabi, there is a 2-second sleep / freeze in the program after it finishes drawing which I guess causes the cursor to be busy. Does that match what you experienced? It is an intended outcome as of now.

**Comment by pouryatorabi** [comment]
Yes that is what causes the problem, but what if we actually need a delay?

**Comment by veeableful** [comment]
Hi @pouryatorabi, you can use the delay function on another thread if needed so it doesn't block the main thread. If you block the main thread with sleep, the cursor will be shown busy.
