### ISSUE TITLE
Window is not visible

### ISSUE THREAD

**Issue by jendave** [veandco/go-sdl2-examples#4]
I am running the examples on MacOS Mojave and the window never appears even though the app icon shows the app is running in the task bar. If I call
`sdl.PollEvent()` or `sdl.PumpEvents()` just before the `sdl.Delay(2000)` line, then the window displays just fine. This happens for all of the examples that do not use an event loop.

**Comment by veeableful** [comment]
Nice find @jendave! Thanks for the tip and the fix. It seems to be occuring on the C examples too. I have updated the examples to include the fix.

**Comment by jendave** [comment]
Thanks! I added a PR for the "render" example.

**Comment by veeableful** [comment]
Ahh thanks!
